#!/usr/bin/env bash
# Generate the ready-to-run install/uninstall scripts under dist/.
#
# Objects are emitted in folder/name order (00-schema -> 10-internal ->
# 20-public), which encodes the dependency order: scalar UDFs require their
# referenced objects to already exist. uninstall.sql drops everything in the
# reverse order, then the schema.
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p dist
INSTALL="dist/typeid-install.sql"
UNINSTALL="dist/typeid-uninstall.sql"

# Object files, in creation order (the schema file is handled separately).
OBJECT_FILES=(sql/10-internal/*.sql sql/20-public/*.sql)

# Schema-qualified object name from a path: strip the "NN-" prefix and ".sql".
object_name() {
    local base
    base="$(basename "$1" .sql)"
    echo "${base#*-}"          # e.g. 20-typeid.NewUuidV7 -> typeid.NewUuidV7
}

# ---- install.sql ----------------------------------------------------------
{
    echo "-- Generated by build.sh -- do not edit by hand."
    echo "-- TypeId for SQL Server 2025. Requires database compatibility level 170."
    echo
    for f in sql/00-schema/*.sql "${OBJECT_FILES[@]}"; do
        echo "-- ===== ${f} ====="
        cat "$f"              # each source already ends with its own GO separator
        echo
    done
} > "$INSTALL"

# ---- uninstall.sql --------------------------------------------------------
{
    echo "-- Generated by build.sh -- do not edit by hand."
    echo "-- Removes every TypeId object and the typeid schema."
    echo
    # Reverse dependency order.
    for (( i=${#OBJECT_FILES[@]}-1; i>=0; i-- )); do
        f="${OBJECT_FILES[$i]}"
        name="$(object_name "$f")"
        if grep -qiE 'CREATE[[:space:]]+(OR[[:space:]]+ALTER[[:space:]]+)?VIEW' "$f"; then
            echo "DROP VIEW IF EXISTS ${name};"
        else
            echo "DROP FUNCTION IF EXISTS ${name};"
        fi
    done
    echo "GO"
    echo "DROP SCHEMA IF EXISTS typeid;"
    echo "GO"
} > "$UNINSTALL"

echo "Wrote ${INSTALL}"
echo "Wrote ${UNINSTALL}"
